export const vaccines = [
  {
    id: 0,
    nom: 'BBIBP-CorV',
    inventeurs: ['Sinopharm'],
    lieux_production: ['Chine'],
    technologie: 'virus inactivé',
    quantité: 420,
    prix_unitaire: 17,
    approuvé: true,
  },
  {
    id: 1,
    nom: 'Sputnik V',
    inventeurs: ['Gamaleya'],
    lieux_production: ['Russie', 'Inde'],
    technologie: 'adenovirus',
    quantité: 130,
    prix_unitaire: 12,
    approuvé: false,
  },
  {
    id: 2,
    nom: 'AZD1222',
    inventeurs: ['AstraZeneca', 'University of Oxford'],
    lieux_production: ['Royaume Unis', 'Brésil', 'Inde'],
    technologie: 'adenovirus',
    quantité: 5028,
    prix_unitaire: 1.78,
    approuvé: false,
  },
  {
    id: 3,
    nom: 'Tozinameran',
    inventeurs: ['BioNTech', 'Pfizer', 'Fosun Pharma'],
    lieux_production: ['Allemagne', 'USA'],
    technologie: 'ARN messager',
    quantité: 980,
    prix_unitaire: 14,
    approuvé: true,
  },
  {
    id: 4,
    nom: 'mRNA-1273',
    inventeurs: ['Moderna', 'NIAID', 'BARDA'],
    lieux_production: ['USA'],
    technologie: 'ARN messager',
    quantité: 240,
    prix_unitaire: 28,
    approuvé: false,
  },
  {
    id: 5,
    nom: 'Ad26.COV2.S',
    inventeurs: ['Johnson & Johnson', 'BIDMC'],
    lieux_production: ['USA', 'Amérique du Sud', 'Ukraine', 'Afrique du Sud'],
    technologie: 'adenovirus',
    quantité: 110,
    prix_unitaire: 31,
    approuvé: false,
  },
];
